### ISSUE TITLE
/Workspace not present in 9.1 LTS

### ISSUE THREAD

**Issue by drernie** [databricks/files_in_repos#3]
I'm not sure what I'm doing wrong, but I can't get this to work on my current DataBricks Cluster
<img width="1148" alt="Screen Shot 2022-01-13 at 7 05 36 PM" src="https://user-images.githubusercontent.com/19791/149444636-3543343b-8333-40d8-bf0b-07803a5cd4b6.png">

**Comment by drernie** [comment]
I see Workspace when  I do `ls /` but when I try to `ls /Workspace` or `Workspace/Repos` I get:
```
ls: cannot access '/Workspace/Repos': Resource temporarily unavailable
```

**Comment by cbleuler** [comment]
I get the same issue here. Both with 9.1 LTS and the newest (10.2).

**Comment by cbleuler** [comment]
Did you enable the support for files in Databricks Repos in the Admin Console?
https://docs.microsoft.com/en-us/azure/databricks/repos

**Comment by drernie** [comment]
Ah.  You're right, it was NOT enabled.

Every time I used the GitHub pane, I thought it was saying I *had* enabled it, which confused me.

Restarting with that on, let's see if it works...
Done. Works. Thanks!

**Comment by drernie** [comment]
Hmm.  Maybe not.
Settings -> Admin Console -> Workspace Settings -> Repos -> Files in Repos: Enabled

I can see the path -- but only Notebook files

I wonder if I need to disconnect and reconnect the Repo for it to work...

**Comment by drernie** [comment]
Yeah, that did it. Once I deleted and re-added the repo, everything worked.

(Except for line 10 which I had to edit; might be nice to explain the UI for how to find and edit files, as I found it non-intuitive: going back to the Repo, then double-clicking, and trusting auto-save.
